/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cardapio.JFrames;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import cardapio.Item;
import cardapio.Sabor;

/**
 *
 * @author Paulo
 */
public class CadastrosJFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form Cadastros
     */
    ArrayList<Item> ListaItensTamanhoUnico = new ArrayList();
    ArrayList<Item> ListaTipoSorvete = new ArrayList();
    ArrayList<Sabor> ListaTodosSabores = new ArrayList();
    
    public CadastrosJFrame() {
        initComponents();
        jInternalFrameCadastrarItem.setVisible(false);
        jInternalRelatorios.setVisible(false);
        jInternalFrameCadastrarNovoSabor.setVisible(false);
        jInternalFrameCadastrarTipoSorvetes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalRelatorios = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton_Relatorio_OK = new javax.swing.JButton();
        jInternalFrameCadastrarTipoSorvetes1 = new javax.swing.JInternalFrame();
        jButtonTipoSorveteCadastroListar1 = new javax.swing.JButton();
        jButton_Cadastar_Sorvete_Salvar1 = new javax.swing.JButton();
        jButton_Cadastar_TipoSorvete_Cancelar1 = new javax.swing.JButton();
        jLabel_Nome_Do_Produto9 = new javax.swing.JLabel();
        jLabel_Nome_Do_Produto11 = new javax.swing.JLabel();
        jComboBoxTodosSabores = new javax.swing.JComboBox();
        jComboBoxTodosTipoSorvete = new javax.swing.JComboBox();
        jInternalFrameCadastrarTipoSorvetes = new javax.swing.JInternalFrame();
        jButtonTipoSorveteCadastroListar = new javax.swing.JButton();
        jButton_Cadastar_Sorvete_Salvar = new javax.swing.JButton();
        jButton_Cadastar_TipoSorvete_Cancelar = new javax.swing.JButton();
        jText_Cadastar_Sorvete_Name = new javax.swing.JTextField();
        jLabel_Nome_Do_Produto6 = new javax.swing.JLabel();
        jLabel_Nome_Do_Produto7 = new javax.swing.JLabel();
        jText_Cadastar_Sorvete_Preco = new javax.swing.JTextField();
        jText_Cadastar_Sorvete_Tamanho_Name = new javax.swing.JTextField();
        jLabel_Nome_Do_Produto8 = new javax.swing.JLabel();
        jInternalFrameCadastrarNovoSabor = new javax.swing.JInternalFrame();
        jButtonSaborCadastroListar = new javax.swing.JButton();
        jButton_Cadastar_Sabor_Salvar = new javax.swing.JButton();
        jButton_Cadastar_Sabor_Cancelar = new javax.swing.JButton();
        jText_Cadastar_Sabor = new javax.swing.JTextField();
        jLabel_Nome_Do_Produto3 = new javax.swing.JLabel();
        jInternalFrameCadastrarItem = new javax.swing.JInternalFrame();
        jButtonItemCadastroListar = new javax.swing.JButton();
        jButton_Cadastar_Item_Salvar = new javax.swing.JButton();
        jButton_Cadastar_Item_Cancelar = new javax.swing.JButton();
        jText_Cadastar_Item_Name = new javax.swing.JTextField();
        jLabel_Nome_Do_Produto = new javax.swing.JLabel();
        jLabel_Nome_Do_Produto1 = new javax.swing.JLabel();
        jText_Cadastar_Item_Preco = new javax.swing.JTextField();
        jText_Cadastar_Item_Tamanho_Name = new javax.swing.JTextField();
        jLabel_Nome_Do_Produto2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuCadastrarBar = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSabor = new javax.swing.JMenuItem();
        jMenuItemTipoSorvete = new javax.swing.JMenuItem();
        jMenuItemSorvete = new javax.swing.JMenuItem();
        jMenuItemOutros = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalRelatorios.setTitle("Relatório");
        jInternalRelatorios.setVisible(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(200, 200, 200));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton_Relatorio_OK.setBackground(new java.awt.Color(200, 255, 200));
        jButton_Relatorio_OK.setText("OK");
        jButton_Relatorio_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Relatorio_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalRelatoriosLayout = new javax.swing.GroupLayout(jInternalRelatorios.getContentPane());
        jInternalRelatorios.getContentPane().setLayout(jInternalRelatoriosLayout);
        jInternalRelatoriosLayout.setHorizontalGroup(
            jInternalRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jInternalRelatoriosLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButton_Relatorio_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jInternalRelatoriosLayout.setVerticalGroup(
            jInternalRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalRelatoriosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Relatorio_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalRelatorios);
        jInternalRelatorios.setBounds(110, 30, 370, 440);

        jInternalFrameCadastrarTipoSorvetes1.setTitle("Cadastrar Novo Sorvete");
        jInternalFrameCadastrarTipoSorvetes1.setPreferredSize(new java.awt.Dimension(489, 250));
        jInternalFrameCadastrarTipoSorvetes1.setVisible(false);

        jButtonTipoSorveteCadastroListar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/btn_ListIcon.png"))); // NOI18N
        jButtonTipoSorveteCadastroListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTipoSorveteCadastroListar1ActionPerformed(evt);
            }
        });

        jButton_Cadastar_Sorvete_Salvar1.setBackground(new java.awt.Color(200, 255, 200));
        jButton_Cadastar_Sorvete_Salvar1.setText("Cadastrar");
        jButton_Cadastar_Sorvete_Salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_Sorvete_Salvar1ActionPerformed(evt);
            }
        });

        jButton_Cadastar_TipoSorvete_Cancelar1.setBackground(new java.awt.Color(255, 200, 200));
        jButton_Cadastar_TipoSorvete_Cancelar1.setText("Cancelar");
        jButton_Cadastar_TipoSorvete_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_TipoSorvete_Cancelar1ActionPerformed(evt);
            }
        });

        jLabel_Nome_Do_Produto9.setText("Tipo:");

        jLabel_Nome_Do_Produto11.setText("Sabor:");

        jComboBoxTodosSabores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxTodosTipoSorvete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTodosTipoSorvete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTodosTipoSorveteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastrarTipoSorvetes1Layout = new javax.swing.GroupLayout(jInternalFrameCadastrarTipoSorvetes1.getContentPane());
        jInternalFrameCadastrarTipoSorvetes1.getContentPane().setLayout(jInternalFrameCadastrarTipoSorvetes1Layout);
        jInternalFrameCadastrarTipoSorvetes1Layout.setHorizontalGroup(
            jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createSequentialGroup()
                .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton_Cadastar_TipoSorvete_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Nome_Do_Produto9)
                            .addComponent(jLabel_Nome_Do_Produto11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTodosSabores, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTodosTipoSorvete, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton_Cadastar_Sorvete_Salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTipoSorveteCadastroListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jInternalFrameCadastrarTipoSorvetes1Layout.setVerticalGroup(
            jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastrarTipoSorvetes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonTipoSorveteCadastroListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTodosTipoSorvete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Nome_Do_Produto9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTodosSabores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Nome_Do_Produto11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastrarTipoSorvetes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cadastar_Sorvete_Salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastar_TipoSorvete_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jInternalFrameCadastrarTipoSorvetes1);
        jInternalFrameCadastrarTipoSorvetes1.setBounds(110, 70, 489, 250);

        jInternalFrameCadastrarTipoSorvetes.setTitle("Cadastrar Novo Tipo de Sorvete");
        jInternalFrameCadastrarTipoSorvetes.setPreferredSize(new java.awt.Dimension(489, 250));
        jInternalFrameCadastrarTipoSorvetes.setVisible(false);

        jButtonTipoSorveteCadastroListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/btn_ListIcon.png"))); // NOI18N
        jButtonTipoSorveteCadastroListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTipoSorveteCadastroListarActionPerformed(evt);
            }
        });

        jButton_Cadastar_Sorvete_Salvar.setBackground(new java.awt.Color(200, 255, 200));
        jButton_Cadastar_Sorvete_Salvar.setText("Cadastrar");
        jButton_Cadastar_Sorvete_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_Sorvete_SalvarActionPerformed(evt);
            }
        });

        jButton_Cadastar_TipoSorvete_Cancelar.setBackground(new java.awt.Color(255, 200, 200));
        jButton_Cadastar_TipoSorvete_Cancelar.setText("Cancelar");
        jButton_Cadastar_TipoSorvete_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_TipoSorvete_CancelarActionPerformed(evt);
            }
        });

        jText_Cadastar_Sorvete_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Cadastar_Sorvete_NameActionPerformed(evt);
            }
        });

        jLabel_Nome_Do_Produto6.setText("Nome do Sorvete");

        jLabel_Nome_Do_Produto7.setText("Preço:");

        jText_Cadastar_Sorvete_Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Cadastar_Sorvete_PrecoActionPerformed(evt);
            }
        });

        jText_Cadastar_Sorvete_Tamanho_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Cadastar_Sorvete_Tamanho_NameActionPerformed(evt);
            }
        });

        jLabel_Nome_Do_Produto8.setText("Tamanho (Opcional):");

        javax.swing.GroupLayout jInternalFrameCadastrarTipoSorvetesLayout = new javax.swing.GroupLayout(jInternalFrameCadastrarTipoSorvetes.getContentPane());
        jInternalFrameCadastrarTipoSorvetes.getContentPane().setLayout(jInternalFrameCadastrarTipoSorvetesLayout);
        jInternalFrameCadastrarTipoSorvetesLayout.setHorizontalGroup(
            jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jButton_Cadastar_TipoSorvete_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                                .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Nome_Do_Produto6)
                                    .addComponent(jLabel_Nome_Do_Produto8)
                                    .addComponent(jLabel_Nome_Do_Produto7))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jText_Cadastar_Sorvete_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(jText_Cadastar_Sorvete_Tamanho_Name)
                                    .addComponent(jText_Cadastar_Sorvete_Preco)))))
                    .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton_Cadastar_Sorvete_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTipoSorveteCadastroListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jInternalFrameCadastrarTipoSorvetesLayout.setVerticalGroup(
            jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Nome_Do_Produto7)
                            .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                                .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jText_Cadastar_Sorvete_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Nome_Do_Produto6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jText_Cadastar_Sorvete_Tamanho_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Nome_Do_Produto8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_Cadastar_Sorvete_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastrarTipoSorvetesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonTipoSorveteCadastroListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastrarTipoSorvetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cadastar_Sorvete_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastar_TipoSorvete_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jInternalFrameCadastrarTipoSorvetes);
        jInternalFrameCadastrarTipoSorvetes.setBounds(110, 70, 489, 250);

        jInternalFrameCadastrarNovoSabor.setTitle("Cadastrar Novo Sabor");
        jInternalFrameCadastrarNovoSabor.setPreferredSize(new java.awt.Dimension(489, 250));
        jInternalFrameCadastrarNovoSabor.setVisible(false);

        jButtonSaborCadastroListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/btn_ListIcon.png"))); // NOI18N
        jButtonSaborCadastroListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaborCadastroListarActionPerformed(evt);
            }
        });

        jButton_Cadastar_Sabor_Salvar.setBackground(new java.awt.Color(200, 255, 200));
        jButton_Cadastar_Sabor_Salvar.setText("Cadastrar");
        jButton_Cadastar_Sabor_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_Sabor_SalvarActionPerformed(evt);
            }
        });

        jButton_Cadastar_Sabor_Cancelar.setBackground(new java.awt.Color(255, 200, 200));
        jButton_Cadastar_Sabor_Cancelar.setText("Cancelar");
        jButton_Cadastar_Sabor_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_Sabor_CancelarActionPerformed(evt);
            }
        });

        jText_Cadastar_Sabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Cadastar_SaborActionPerformed(evt);
            }
        });

        jLabel_Nome_Do_Produto3.setText("Nome do Sabor");

        javax.swing.GroupLayout jInternalFrameCadastrarNovoSaborLayout = new javax.swing.GroupLayout(jInternalFrameCadastrarNovoSabor.getContentPane());
        jInternalFrameCadastrarNovoSabor.getContentPane().setLayout(jInternalFrameCadastrarNovoSaborLayout);
        jInternalFrameCadastrarNovoSaborLayout.setHorizontalGroup(
            jInternalFrameCadastrarNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarNovoSaborLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jButton_Cadastar_Sabor_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrameCadastrarNovoSaborLayout.createSequentialGroup()
                .addGroup(jInternalFrameCadastrarNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarNovoSaborLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton_Cadastar_Sabor_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameCadastrarNovoSaborLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_Nome_Do_Produto3)
                        .addGap(18, 18, 18)
                        .addComponent(jText_Cadastar_Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButtonSaborCadastroListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jInternalFrameCadastrarNovoSaborLayout.setVerticalGroup(
            jInternalFrameCadastrarNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastrarNovoSaborLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jInternalFrameCadastrarNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jText_Cadastar_Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Nome_Do_Produto3))
                    .addComponent(jButtonSaborCadastroListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastrarNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cadastar_Sabor_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastar_Sabor_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jInternalFrameCadastrarNovoSabor);
        jInternalFrameCadastrarNovoSabor.setBounds(110, 70, 489, 250);

        jInternalFrameCadastrarItem.setTitle("Cadastrar Novo Item");
        jInternalFrameCadastrarItem.setPreferredSize(new java.awt.Dimension(489, 250));
        jInternalFrameCadastrarItem.setVisible(false);

        jButtonItemCadastroListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/btn_ListIcon.png"))); // NOI18N
        jButtonItemCadastroListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItemCadastroListarActionPerformed(evt);
            }
        });

        jButton_Cadastar_Item_Salvar.setBackground(new java.awt.Color(200, 255, 200));
        jButton_Cadastar_Item_Salvar.setText("Cadastrar");
        jButton_Cadastar_Item_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_Item_SalvarActionPerformed(evt);
            }
        });

        jButton_Cadastar_Item_Cancelar.setBackground(new java.awt.Color(255, 200, 200));
        jButton_Cadastar_Item_Cancelar.setText("Cancelar");
        jButton_Cadastar_Item_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastar_Item_CancelarActionPerformed(evt);
            }
        });

        jText_Cadastar_Item_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Cadastar_Item_NameActionPerformed(evt);
            }
        });

        jLabel_Nome_Do_Produto.setText("Nome do Produto:");

        jLabel_Nome_Do_Produto1.setText("Preço:");

        jText_Cadastar_Item_Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Cadastar_Item_PrecoActionPerformed(evt);
            }
        });

        jText_Cadastar_Item_Tamanho_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Cadastar_Item_Tamanho_NameActionPerformed(evt);
            }
        });

        jLabel_Nome_Do_Produto2.setText("Tamanho (Opcional):");

        javax.swing.GroupLayout jInternalFrameCadastrarItemLayout = new javax.swing.GroupLayout(jInternalFrameCadastrarItem.getContentPane());
        jInternalFrameCadastrarItem.getContentPane().setLayout(jInternalFrameCadastrarItemLayout);
        jInternalFrameCadastrarItemLayout.setHorizontalGroup(
            jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarItemLayout.createSequentialGroup()
                .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameCadastrarItemLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jButton_Cadastar_Item_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrameCadastrarItemLayout.createSequentialGroup()
                                .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Nome_Do_Produto)
                                    .addComponent(jLabel_Nome_Do_Produto2)
                                    .addComponent(jLabel_Nome_Do_Produto1))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_Cadastar_Item_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText_Cadastar_Item_Tamanho_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText_Cadastar_Item_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jInternalFrameCadastrarItemLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton_Cadastar_Item_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonItemCadastroListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jInternalFrameCadastrarItemLayout.setVerticalGroup(
            jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastrarItemLayout.createSequentialGroup()
                .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarItemLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Nome_Do_Produto1)
                            .addGroup(jInternalFrameCadastrarItemLayout.createSequentialGroup()
                                .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jText_Cadastar_Item_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Nome_Do_Produto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jText_Cadastar_Item_Tamanho_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Nome_Do_Produto2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_Cadastar_Item_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastrarItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonItemCadastroListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastrarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cadastar_Item_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastar_Item_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jInternalFrameCadastrarItem);
        jInternalFrameCadastrarItem.setBounds(110, 70, 489, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/bg_cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 500);

        jMenuCadastrar.setText("Cadastrar");

        jMenu1.setText("Sorvete");

        jMenuItemSabor.setText("Novo Sabor");
        jMenuItemSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaborActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSabor);

        jMenuItemTipoSorvete.setText("Novo Tipo Sorvete");
        jMenuItemTipoSorvete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoSorveteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTipoSorvete);

        jMenuItemSorvete.setText("Novo Sorvete");
        jMenu1.add(jMenuItemSorvete);

        jMenuCadastrar.add(jMenu1);

        jMenuItemOutros.setText("Outros");
        jMenuItemOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOutrosActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemOutros);

        jMenuCadastrarBar.add(jMenuCadastrar);

        jMenuAjuda.setText("Ajuda");

        jMenuAbout.setText("Sobre");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuAbout);

        jMenuCadastrarBar.add(jMenuAjuda);

        setJMenuBar(jMenuCadastrarBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Software desenvolvido por: \n Flávio \n Paulo \n\n versão: 0.1"); 
        //MENU AJUDA>SOBRE
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jMenuItemOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOutrosActionPerformed
        jInternalFrameCadastrarItem.setVisible(true);
        //MENU OUTROS(ITENS)
    }//GEN-LAST:event_jMenuItemOutrosActionPerformed

    private void jButton_Cadastar_Item_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_Item_SalvarActionPerformed

        if(!jText_Cadastar_Item_Tamanho_Name.getText().equals("")){
            Item item = new Item(jText_Cadastar_Item_Name.getText(),jText_Cadastar_Item_Tamanho_Name.getText(),Float.parseFloat(jText_Cadastar_Item_Preco.getText()));
            ListaItensTamanhoUnico.add(item);
        }
        else{
             Item item = new Item(jText_Cadastar_Item_Name.getText(),Float.parseFloat(jText_Cadastar_Item_Preco.getText()));
             ListaItensTamanhoUnico.add(item);
        }
        
        jText_Cadastar_Item_Name.setText(null);
        jText_Cadastar_Item_Tamanho_Name.setText(null);
        jText_Cadastar_Item_Preco.setText(null);
        //CADASTRAR ITEM
    }//GEN-LAST:event_jButton_Cadastar_Item_SalvarActionPerformed

    private void jButton_Cadastar_Item_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_Item_CancelarActionPerformed
        jText_Cadastar_Item_Name.setText(null);
        jText_Cadastar_Item_Tamanho_Name.setText(null);
        jText_Cadastar_Item_Preco.setText(null);
        jInternalFrameCadastrarItem.setVisible(false);
        //BOTAO CANCELAR ITEM
    }//GEN-LAST:event_jButton_Cadastar_Item_CancelarActionPerformed

    private void jText_Cadastar_Item_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Cadastar_Item_NameActionPerformed

    }//GEN-LAST:event_jText_Cadastar_Item_NameActionPerformed

    private void jText_Cadastar_Item_PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Cadastar_Item_PrecoActionPerformed

    }//GEN-LAST:event_jText_Cadastar_Item_PrecoActionPerformed

    private void jText_Cadastar_Item_Tamanho_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Cadastar_Item_Tamanho_NameActionPerformed

    }//GEN-LAST:event_jText_Cadastar_Item_Tamanho_NameActionPerformed

    private void jButtonItemCadastroListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItemCadastroListarActionPerformed
       jInternalRelatorios.setVisible(true);
        jTextArea1.setText(null);
        for(int i = 0; i < ListaItensTamanhoUnico.size(); i++){
            jTextArea1.append(ListaItensTamanhoUnico.get(i).print()+"\n");
        }
        //RELATORIO ITEM
    }//GEN-LAST:event_jButtonItemCadastroListarActionPerformed

    private void jButton_Relatorio_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Relatorio_OKActionPerformed
        jInternalRelatorios.setVisible(false);
        // BOTAO OK RELATORIO
    }//GEN-LAST:event_jButton_Relatorio_OKActionPerformed

    private void jMenuItemSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaborActionPerformed

        jInternalFrameCadastrarNovoSabor.setVisible(true);
        //MENU SABOR
    }//GEN-LAST:event_jMenuItemSaborActionPerformed

    private void jButtonSaborCadastroListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaborCadastroListarActionPerformed
        jInternalRelatorios.setVisible(true);
        jTextArea1.setText(null);
        for(int i = 0; i < ListaTodosSabores.size(); i++){
            jTextArea1.append(ListaTodosSabores.get(i).print()+"\n");
        } 
        //RELATORIO SABORES
    }//GEN-LAST:event_jButtonSaborCadastroListarActionPerformed

    private void jButton_Cadastar_Sabor_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_Sabor_SalvarActionPerformed
        Sabor item = new Sabor(jText_Cadastar_Sabor.getText());
        ListaTodosSabores.add(item);
        jText_Cadastar_Sabor.setText(null);
        //CADASTRAR SABOR
    }//GEN-LAST:event_jButton_Cadastar_Sabor_SalvarActionPerformed

    private void jButton_Cadastar_Sabor_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_Sabor_CancelarActionPerformed

        jText_Cadastar_Sabor.setText(null);
        jInternalFrameCadastrarNovoSabor.setVisible(false);
        //BOTAO CANCELAR DO SABOR
    }//GEN-LAST:event_jButton_Cadastar_Sabor_CancelarActionPerformed

    private void jText_Cadastar_SaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Cadastar_SaborActionPerformed

    }//GEN-LAST:event_jText_Cadastar_SaborActionPerformed

    private void jMenuItemTipoSorveteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoSorveteActionPerformed
        jInternalFrameCadastrarTipoSorvetes.setVisible(true);
        //MENU TIPO SORVETE
    }//GEN-LAST:event_jMenuItemTipoSorveteActionPerformed

    private void jButtonTipoSorveteCadastroListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTipoSorveteCadastroListarActionPerformed
        jInternalRelatorios.setVisible(true);
        jTextArea1.setText(null);
        for(int i = 0; i < ListaTipoSorvete.size(); i++){
            jTextArea1.append(ListaTipoSorvete.get(i).print()+"\n");
        } 
        //RELATOIO TIPOS SORVETE
    }//GEN-LAST:event_jButtonTipoSorveteCadastroListarActionPerformed

    private void jButton_Cadastar_Sorvete_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_Sorvete_SalvarActionPerformed
        if(!jText_Cadastar_Sorvete_Tamanho_Name.getText().equals("")){
            Item item = new Item(jText_Cadastar_Sorvete_Name.getText(),jText_Cadastar_Sorvete_Tamanho_Name.getText(),Float.parseFloat(jText_Cadastar_Sorvete_Preco.getText()));
            ListaTipoSorvete.add(item);
        }
        else{
             Item item = new Item(jText_Cadastar_Sorvete_Name.getText(),Float.parseFloat(jText_Cadastar_Sorvete_Preco.getText()));
             ListaTipoSorvete.add(item);
        }
        
        jText_Cadastar_Sorvete_Name.setText(null);
        jText_Cadastar_Sorvete_Tamanho_Name.setText(null);
        jText_Cadastar_Sorvete_Preco.setText(null);
        //CADASTRAR SORVETE
    }//GEN-LAST:event_jButton_Cadastar_Sorvete_SalvarActionPerformed

    private void jButton_Cadastar_TipoSorvete_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_TipoSorvete_CancelarActionPerformed

        jText_Cadastar_Sorvete_Name.setText(null);
        jText_Cadastar_Sorvete_Tamanho_Name.setText(null);
        jText_Cadastar_Sorvete_Preco.setText(null);
        jInternalFrameCadastrarTipoSorvetes.setVisible(false);
        //BOTAO CANCELAR TIPO SORVETE
    }//GEN-LAST:event_jButton_Cadastar_TipoSorvete_CancelarActionPerformed

    private void jText_Cadastar_Sorvete_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Cadastar_Sorvete_NameActionPerformed

    }//GEN-LAST:event_jText_Cadastar_Sorvete_NameActionPerformed

    private void jText_Cadastar_Sorvete_PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Cadastar_Sorvete_PrecoActionPerformed

    }//GEN-LAST:event_jText_Cadastar_Sorvete_PrecoActionPerformed

    private void jText_Cadastar_Sorvete_Tamanho_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Cadastar_Sorvete_Tamanho_NameActionPerformed

    }//GEN-LAST:event_jText_Cadastar_Sorvete_Tamanho_NameActionPerformed

    private void jButtonTipoSorveteCadastroListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTipoSorveteCadastroListar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTipoSorveteCadastroListar1ActionPerformed

    private void jButton_Cadastar_Sorvete_Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_Sorvete_Salvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Cadastar_Sorvete_Salvar1ActionPerformed

    private void jButton_Cadastar_TipoSorvete_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastar_TipoSorvete_Cancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Cadastar_TipoSorvete_Cancelar1ActionPerformed

    private void jComboBoxTodosTipoSorveteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTodosTipoSorveteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTodosTipoSorveteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonItemCadastroListar;
    private javax.swing.JButton jButtonSaborCadastroListar;
    private javax.swing.JButton jButtonTipoSorveteCadastroListar;
    private javax.swing.JButton jButtonTipoSorveteCadastroListar1;
    private javax.swing.JButton jButton_Cadastar_Item_Cancelar;
    private javax.swing.JButton jButton_Cadastar_Item_Salvar;
    private javax.swing.JButton jButton_Cadastar_Sabor_Cancelar;
    private javax.swing.JButton jButton_Cadastar_Sabor_Salvar;
    private javax.swing.JButton jButton_Cadastar_Sorvete_Salvar;
    private javax.swing.JButton jButton_Cadastar_Sorvete_Salvar1;
    private javax.swing.JButton jButton_Cadastar_TipoSorvete_Cancelar;
    private javax.swing.JButton jButton_Cadastar_TipoSorvete_Cancelar1;
    private javax.swing.JButton jButton_Relatorio_OK;
    private javax.swing.JComboBox jComboBoxTodosSabores;
    private javax.swing.JComboBox jComboBoxTodosTipoSorvete;
    private javax.swing.JInternalFrame jInternalFrameCadastrarItem;
    private javax.swing.JInternalFrame jInternalFrameCadastrarNovoSabor;
    private javax.swing.JInternalFrame jInternalFrameCadastrarTipoSorvetes;
    private javax.swing.JInternalFrame jInternalFrameCadastrarTipoSorvetes1;
    private javax.swing.JInternalFrame jInternalRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Nome_Do_Produto;
    private javax.swing.JLabel jLabel_Nome_Do_Produto1;
    private javax.swing.JLabel jLabel_Nome_Do_Produto11;
    private javax.swing.JLabel jLabel_Nome_Do_Produto2;
    private javax.swing.JLabel jLabel_Nome_Do_Produto3;
    private javax.swing.JLabel jLabel_Nome_Do_Produto6;
    private javax.swing.JLabel jLabel_Nome_Do_Produto7;
    private javax.swing.JLabel jLabel_Nome_Do_Produto8;
    private javax.swing.JLabel jLabel_Nome_Do_Produto9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuBar jMenuCadastrarBar;
    private javax.swing.JMenuItem jMenuItemOutros;
    private javax.swing.JMenuItem jMenuItemSabor;
    private javax.swing.JMenuItem jMenuItemSorvete;
    private javax.swing.JMenuItem jMenuItemTipoSorvete;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jText_Cadastar_Item_Name;
    private javax.swing.JTextField jText_Cadastar_Item_Preco;
    private javax.swing.JTextField jText_Cadastar_Item_Tamanho_Name;
    private javax.swing.JTextField jText_Cadastar_Sabor;
    private javax.swing.JTextField jText_Cadastar_Sorvete_Name;
    private javax.swing.JTextField jText_Cadastar_Sorvete_Preco;
    private javax.swing.JTextField jText_Cadastar_Sorvete_Tamanho_Name;
    // End of variables declaration//GEN-END:variables
}
